version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20.x
  pre_build:
    commands:
      - echo In the pre_build phase...
      - ls -la
      - cd "vite-project"
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - ls -la
      # - cd "vite-project"
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  base-directory: 'vite-project/dist'
  discard-paths: no